### ISSUE TITLE
Incorrect UI, missing all labels. (Macbook Pro, macOS Mojave)

### ISSUE THREAD

**Issue by bstro** [ephtracy/ephtracy.github.io#128]
Hi there,

This is a new one for me, different from the common blank UI issue. When starting MagicaVoxel 0.99.3, I get the following UI. I don't think this is correct. It looks like a lot of stuff is missing.
<img width="1162" alt="screen shot 2019-03-04 at 3 37 54 pm" src="https://user-images.githubusercontent.com/627290/53761465-92788f80-3e93-11e9-8061-72c5b4728fb2.png">

**Comment by bstro** [comment]
I did some snooping around and see this from the logs that are output to the terminal if you run the executable directly:

```
unable to load font texture : /Applications/MagicaVoxel-0.99.3-alpha-macos/config/font/font-Calibri-bold.png
unable to load font texture : /Applications/MagicaVoxel-0.99.3-alpha-macos/config/font/font-Consolas-bold.png
```

**Comment by bstro** [comment]
Another update, this issue persists even after re-installing.

**Comment by eynol** [comment]
Pooh! Case-sensetive file system!
I noticed that the word `Calibri` is uppercase in `font-Calibri-bold.png` , which on my disk is `calibri`.

The labels came back after I renamed `font-calibri-bold.png`  and `font-consolas-bold.png`  to `font-Calibri-bold.png` and `font-Consolas-bold.png`.

Have a try~
