### ISSUE TITLE
Does not work on MacOS High Sierra 10.13.6

### ISSUE THREAD

**Issue by chiefmonky** [ephtracy/ephtracy.github.io#140]
Would love to use this on CryptoVoxels but just get a white screen on starting up.

I've tried version 0.99.4.2 and 0.99.4 

Really hope you can fix this... heard lots of good things... I'm getting major FOMO

**Comment by rednaxelafs** [comment]
I also got white screen on MacOS 10.13.6 for 0.99.4.
MagicaVoxel-0.99.4.2-alpha-macos/MagicaVoxel.app/Contents/MacOS/MagicaVoxel
Executing directly the binary from the path above seem to work, no idea if there were missing dependencies.

**Comment by johshoff** [comment]
This is a known issue. Try

> Move MagicaVoxel.app outside the folder and then back to it

From https://mvc.wiki/m/MagicaVoxel

(you should close the issue if it works)

**Comment by chiefmonky** [comment]
@johshoff thank you so much for your help... I've sent you a Brave Tips (BAT) don't know if you use the Brave browser bu thank you... 

@rednaxelafs the answer is here https://mvc.wiki/m/MagicaVoxel - Installing MagicaVoxel - Apple Mac OS section
