### ISSUE TITLE
MagicaVoxel 0.99.5: Оbjects in Model mode are not displayed.

### ISSUE THREAD

**Issue by maxkorsov** [ephtracy/ephtracy.github.io#147]
I don’t see objects in Model mode. There is no way to draw objects. The cursor moves in empty space. In Rendering mode, the object is visible.
This problem is relevant for win32/win64 versions.

All the drivers on my PC have current versions.
I remain on the version of 0.99.4.2 win64 for now.

Perhaps the program has changed the minimum requirements.
Here are the data of my PC (there are no problems with version 0.99.4.2 win64):
- Intel Core i7 4702MQ - 2.20GHz
- 16,0GB DDR3
- Intel HD Graphics 4600 / NVIDIA GeForce GT 750M - 2GB
- 256GB SSD / 2000GB HDD
- Windows 10 Pro ver.1909 (64bit)

**Comment by maxkorsov** [comment]
Screenshots: MagicaVoxel 0.99.5 win64

Model mode:
<a href="https://funkyimg.com/view/33GsK" target="_blank"><img src="https://funkyimg.com/i/33GsK.png" alt="MagicaVoxel 0.99.5 win64: Model mode" border="0"></a>

Render mode:
<a href="https://funkyimg.com/view/33GsN" target="_blank"><img src="https://funkyimg.com/i/33GsN.png" alt="MagicaVoxel 0.99.5 win64: Render mode" border="0"></a>

**Comment by ephtracy** [comment]
Hi, are you able to force the program using GT 750M?

**Comment by maxkorsov** [comment]
Hi!
I followed your advice. Yes, it turned out to force start using GT 750M. Everything works.
<a href="https://funkyimg.com/view/33GDe" target="_blank"><img src="https://funkyimg.com/i/33GDe.png" alt="Force start using GT 750M" border="0"></a>

This means that the program has problems with the Intel HD Graphics 4600. Can this be fixed?

**Comment by Chevin218** [comment]
I'm running into the same issue, my hardware config is:
Intel HD Graphics 630 - No visible model"
NVidia Geforce GTX 1070 - Everything is visible

Keep up the good work @ephtracy, MagicaVoxel is one hell of a program!

**Comment by ephtracy** [comment]
Hi, I uploaded an update of the program to fix this rendering bug along with some other editing commands bugs. can you try it out? Thank you.

**Comment by Chevin218** [comment]
Where is the update located?

**Comment by ephtracy** [comment]
the same link on the home page

**Comment by Chevin218** [comment]
When i press 0.99.5 on https://ephtracy.github.io/ it takes me to https://github.com/ephtracy/ephtracy.github.io/releases/tag/0.99.5 which is the version that i've got installed.

**Comment by ephtracy** [comment]
the win64 version

**Comment by ephtracy** [comment]
I mean I have updated the package on that page

**Comment by Chevin218** [comment]
Can you give me the URL for the update file?
I've just downloaded the file located at https://github.com/ephtracy/ephtracy.github.io/releases/download/0.99.5/MagicaVoxel-0.99.5-alpha-win64.zip and it has the issue.

**Comment by ephtracy** [comment]
can you try out this version? https://drive.google.com/file/d/1gvK3PW3H7QZ-pTIxHSwqkARuuXj3Xxt0/view?usp=sharing

**Comment by Chevin218** [comment]
![image](https://user-images.githubusercontent.com/45685781/78593776-74742000-7847-11ea-81b2-0d12b7954728.png)
I've downloaded the Google Drive file and tried to open some pre-existing models in the right column, so far i have no visible models on my on board graphics.

**Comment by ephtracy** [comment]
here is an updated one: https://drive.google.com/file/d/1gvK3PW3H7QZ-pTIxHSwqkARuuXj3Xxt0/view?usp=sharing

**Comment by ephtracy** [comment]
it's mainly due to some shader compiling errors

**Comment by ephtracy** [comment]
here is an updated version based on some people's feedback: https://github.com/ephtracy/ephtracy.github.io/releases/download/0.99.5/MagicaVoxel-0.99.5-alpha-win64.zip

**Comment by Chevin218** [comment]
Thank you, this fixed the issue for me!

**Comment by ephtracy** [comment]
great to hear:D On the other hand, dedicated cards such as Nvidia/AMD are recommended for better performance.

**Comment by ephtracy** [comment]
a reminder that there is a new update to solve some other rendering and editing bugs.

**Comment by maxkorsov** [comment]
Good job @ephtracy

I checked the fixes for MagicaVoxel 0.99.5 (with Intel HD Graphics 4600):
- Model Mode - Good;
- Render Mode - Good.

Now everything works.
You're cool! Thanks!

**Comment by sohamghoshh** [comment]
![Untitled](https://user-images.githubusercontent.com/81745291/116036674-af303c80-a684-11eb-8ee4-ecae9852b9f0.png)


object visible




![Untitledaa](https://user-images.githubusercontent.com/81745291/116036701-b8210e00-a684-11eb-96c3-1dbd012b3042.png)


objects vanish during render
