### ISSUE TITLE
Problems Contained in 0.99.5

### ISSUE THREAD

**Issue by GreenChennai** [ephtracy/ephtracy.github.io#148]
1. Sawtooth appears around the model
2.When placing the block, it is not as smooth as the old version 0.99.4 have Caton

The download link of MagicaVoxel Viewer on the official website is invalid.
Can you upload the downloaded file to Github?

**Comment by ephtracy** [comment]
1. Sawtooth is caused by lacking of anti-aliasing which will be improved in following updates (but may be expensive).

2. Viewer hasn't been updated for years and is out of date now.

**Comment by GreenChennai** [comment]
Okay, except for aliasing issues
I think the most serious thing is
After the update version, there will be a pause when placing the block
The old version does not have this problem

**Comment by ephtracy** [comment]
the pausing is caused by initialization. for the following strokes, there will be less pause.

**Comment by GreenChennai** [comment]
Okay,Thanks Reply
