### ISSUE TITLE
Having trouble rendering my whole project

### ISSUE THREAD

**Issue by CaptainOfNoShip** [ephtracy/ephtracy.github.io#153]
![image](https://user-images.githubusercontent.com/64783819/80963337-06ebed00-8e0f-11ea-88d6-420237d7c9ef.png)
![image](https://user-images.githubusercontent.com/64783819/80963360-12d7af00-8e0f-11ea-9bb0-994512177049.png)
I'm having trouble rendering my whole project. As you can see in the pictures, only a part of it is loading. Anything that's within that rendered space will render but anything beyond that border won't render whatsoever. I converted all my object to 256x256x256 so that might be the problem because it started after that. I'm using the latest version 0.99.5.

**Comment by ephtracy** [comment]
you can enable Render->Sample->Geometry->Sparse

**Comment by CaptainOfNoShip** [comment]
Thank you! That worked!
