### ISSUE TITLE
Feature Request: Triangles, transparency in marching cubes, rotation

### ISSUE THREAD

**Issue by bigdatamark** [ephtracy/ephtracy.github.io#164]
Feature Requests / Bugs:

1. Transparency doesn't seem to work in MC (Marching Cubes) renders. Providing the algorithm supports this, would like to get it.

2. Would love to have just a simple right triangle along with cubes, aka a cube cut in half at a 45 degree angle.

3. When selecting my model and rotating it z 180, I'm losing parts of my model. Would love for it not to do that.

4. Would love to be able to attach shape (MC/Lego/Cube/etc.) to a material/pallet color instead of having it apply to the entire scene.

That's it. Thanks for the great software!

**Comment by ephtracy** [comment]
1.4. too expensive and  complex to render interactively, not worth the effort.
2. the program will only support axis-aligned grids.
