### ISSUE TITLE
Please add Linux Support

### ISSUE THREAD

**Issue by sebi82** [ephtracy/ephtracy.github.io#172]

**Comment by winkdong** [comment]
AppImage can be great for all distros, or Flatpak.
I find it is much more comfortable to use than [Goxel](https://github.com/guillaumechereau/goxel) for me.
Thank you for this amazing application!

**Comment by v4dkou** [comment]
For anyone else looking for a Linux version, I should mention that Wine works surprisingly well for MagicaVoxel

**Comment by dromer** [comment]
Would also prefer a native version, even though with wine (`wine-4.0 (Debian 4.0-2)` here) it indeed works much better than expected :)

**Comment by gitowiec** [comment]
@ephtracy is there any plans releasing this tool for Linux platform? What would you need to compile MagicalVoxel for Linux?

**Comment by culmat** [comment]
this seems to be a duplicate of #162

**Comment by Shadowblitz16** [comment]
please compile this for linux.

**Comment by dromer** [comment]
Hmm, is that a no?

**Comment by twinflac** [comment]
> Hmm, is that a no?

if guys not do this, maybe anyone else can will

**Comment by dromer** [comment]
> if guys not do this, maybe anyone else can will

MagicaVoxel is not an opensource project.

**Comment by twinflac** [comment]
> MagicaVoxel is not an opensource project.
this is not a limitation)

**Comment by dromer** [comment]
> this is not a limitation)

Er .. how do you propose that anyone would port the software to a different OS (or architecture).. without having access to the source-code?

**Comment by twinflac** [comment]
may be, i know guys that can do this
