### ISSUE TITLE
Will the source code be published in the future?

### ISSUE THREAD

**Issue by theuserbl** [ephtracy/ephtracy.github.io#176]
Currently programs like Goxel, MineCube, etc are OpenSource on GitHub. But what is with this MagicaVoxel?

On the release-page of this MagicaVoxel GitHub page are the binaries and Sourcecode-files (the "Source Code" in zip and tar.gz format).
But the "Source Code" is only the source of the webpage of MagicalVoxel.
What is with the program itself?

**Comment by ephtracy** [comment]
it's a private project not open-sourced.
