### ISSUE TITLE
Supporting 16777216 colors

### ISSUE THREAD

**Issue by theuserbl** [ephtracy/ephtracy.github.io#177]
Add the support for 256 (red) * 256 (green) * 256 (blue) = 16777216 colors.

I am really missing colors. It isn't possible to colorize it with digital photos without loosing colors.
Better would be to support ARGB colors, to have transparency.

RGB supports the simple mspaint.exe in 2D. But in 3D i t isn't possible?
And ARGB supporting more advanced graphic programs. Why not the same in 3D ?

**Comment by ephtracy** [comment]
24-bit color requires more CPU and GPU memory, and different workflow for painting.
that's another story.
