### ISSUE TITLE
Feature Request: free object rotation

### ISSUE THREAD

**Issue by tofoz** [ephtracy/ephtracy.github.io#181]
being able to have free non-axes alined object rotation, meaning the voxels in an object are not aligned to the grid/other objects.

**Comment by hitrpr** [comment]
Done?

**Comment by tofoz** [comment]
you can rotate the voxel data in the volume/object but what I'm referring to is rotating the object its self in the outline tree.
here's an example where the two objects are not axis-aligned, the top and bottom of the skull.
![exam skull](https://user-images.githubusercontent.com/40554706/106956464-79199700-66eb-11eb-92b7-63cbf35197ae.PNG)
with that being said id imagine the way the modeler and render are set up that this may not be possible.

**Comment by ephtracy** [comment]
magicavoxel will only focus on axis-aligned grids.
