### ISSUE TITLE
Blank screen on mac

### ISSUE THREAD

**Issue by edap** [ephtracy/ephtracy.github.io#19]
Hello ephtracy, thank you for your awesome project.
I've tried to install your app on macOS and I've got a black screen. I've extracted the MagicaVoxel.app outside of the extracted folder, as you are suggesting on the website, but the problem persists. I've tried to run the app from the terminal, to see if there are some useful debug information, but there is nothing.

I do not know if this is the right place to submit issues, in case there is another place, let me know.

MacOS El Capitan 10.11.5
MagicaVoxel 0.98.2

**Comment by darkfall** [comment]
"I've extracted the MagicaVoxel.app outside of the extracted folder", have you moved MagicaVoxel.app back to the extracted folder? The .app need to be in the directory as other files (cache, config, ...)

**Comment by edap** [comment]
It worked, thanks ;)

**Comment by arkilis** [comment]
What is the possible reason behind this?

**Comment by darkfall** [comment]
@arkilis macOS security, my guess is the app getting denied when reading files. Though I have no idea why moving the app around solves the problem.

**Comment by arkilis** [comment]
@darkfall I see, so just curious what language to develop MagicaVoxel?

**Comment by mkshukeri** [comment]
I have downloaded the app. Extract the folder. Move the folder to the desktop. Cut the app the desktop and paste it back into the folder which is on the desktop. And it works!

**Comment by jakelacey2012** [comment]
Same problem as previous comment and the fix worked.

**Comment by adrianodelvigna** [comment]
Same issue here. By moving the .app file to some other folder, and then moving it back to the extracted folder solved the issue for me too, as suggested by @mkshukeri.

**Comment by aislanmaia** [comment]
Tried it today with the MagicaVoxel-0.99.1-alpha-win64 version but got the black screen problem. Have you guys tried the 32 bit version or the 64 one ?

**Comment by trejkaz** [comment]
I guess the problem is that on Mac, you're supposed to put the resources inside the application bundle, not next to it.

**Comment by yosowashi** [comment]
I tried installing Windows version into CrossOver and it worked!
