### ISSUE TITLE
Open .vox File asks me to manual open it

### ISSUE THREAD

**Issue by superfrantv** [ephtracy/ephtracy.github.io#194]
Hello,
since i update to newest Version, if i open a .vox file it opens MagicaVoxel but the then it shows me a window, where i need to manualy reopen the vox file.. this seams very time consuming.

sorry for bad englisch iam from germany

**Comment by artnas** [comment]
This also happens to me on 0.99.6.3. Didn't happen on 0.99.5.

**Comment by ephtracy** [comment]
the bug is due to the format changes of related cmds.
it's fixed in the latest update.
