### ISSUE TITLE
0.99.6.3/2 render issues compared to 0.99.4.2-alpha

### ISSUE THREAD

**Issue by Sasquatch89537** [ephtracy/ephtracy.github.io#198]
![image](https://user-images.githubusercontent.com/9869509/108584624-1dacf300-7300-11eb-9ff7-dc4cf81db4ab.png)
Did a fresh install with default settings. 0.99.6.3 and .2  and showing the exact same issues, but appear fine once going into world view. Jumped to 0.99.4.2-alpha and things look just fine.

Not sure if it's from being on a new AMD 6000 series GPU or not.

**Comment by boyweb** [comment]
I've met the same problem and also on the new AMD 6000 series GPU.
![无标题](https://user-images.githubusercontent.com/3590089/108626207-ff72fe80-7489-11eb-9ca7-dd0a72e504f6.png)

**Comment by Sasquatch89537** [comment]
![image](https://user-images.githubusercontent.com/9869509/108894703-d65c8600-75cf-11eb-9b3e-1821f83da526.png)
Unfortunately 0.99.4.2-alpha's rendering gives me grids on the model. It's looking like it's an issue with 6000 series cards.

**Comment by ephtracy** [comment]
will investigate this issue. thanks.

**Comment by Devlin556** [comment]
@Sasquatch89537 The same problem, this is looks like only 6000x series and driver issue. I have an 6800 XT on my desctop PC and default scene "room" doesn't render (only some random voxels but it's semi transparent)  and videocard works with 100% load of GPU but model still doesn't render. 
![image](https://user-images.githubusercontent.com/16045765/125210429-7cbbd600-e2a8-11eb-9a37-296abce8e053.png)
Also, I have an MacBook Pro 16 with Radeon PRO 5500M and magica voxel render works perfectly.

**Comment by Devlin556** [comment]
I also tried all existing versions with 6800 xt - and no one of these doesn't work normally in render. So bad for me.

**Comment by Devlin556** [comment]
@boyweb maybe it is AMD Graphic Driver issue? On macos (i don't know) it works different from windows with drivers for hardware. I also know that AMD has different drivers for creators and gamers, Radeon Adrenaline Blue and Adrenaline Red.

**Comment by ephtracy** [comment]
have figured out the solution for this issue on 6800. please wait for an update by the end of this month.

**Comment by Devlin556** [comment]
@ephtracy Does update for 6800 XT comes soon?

**Comment by CeridianX** [comment]
Came across the same problem on my 6800 XT, would be great to know whether the fix is close.

**Comment by Scottx125** [comment]
Same problem on 6900XT.

**Comment by ephtracy** [comment]
0.99.6.3 is updated to fix the rendering issues on 6800 cards.

**Comment by Devlin556** [comment]
@ephtracy where can I find this version? I found only 0.99.6.2 and 0.99.6.4

**Comment by ephtracy** [comment]
0.99.6.4 is a higher version that includes the fix

**Comment by Devlin556** [comment]
@ephtracy thank you! Now it works, I'm really glad that now I can make voxel models on my PC because MacBook is not a good choice to make this work anymore, the video card on it - is too weak.
