### ISSUE TITLE
It isn’t loading

### ISSUE THREAD

**Issue by Geekster1984** [ephtracy/ephtracy.github.io#200]
When I boot it up, it just gives me a white screen then switches to a pitch black screen! And it was working fine the other 3 or 4 times I’ve used it! Help

**Comment by jdille** [comment]
Same here. I downloaded MagicaVoxel-0.99.6.2-macos-10.15 and on launch got a blank black window and same after trying MagicaVoxel-0.99.4.2-alpha-macos.

**Comment by gnoren** [comment]
Same here, for macos 10.7 I just get a black screen

**Comment by ngochoangjp** [comment]
I have the same issue, here's what i found out:  Right click on the app icon to show package contains, then Contents\MacOS\MagicalVoxel. Just click to open it.

**Comment by ThoastProductions** [comment]
Same problem here.

> I have the same issue, here's what i found out: Right click on the app icon to show package contents, then Contents\MacOS\MagicalVoxel. Just click to open it.

That just opens terminal?

**Comment by Ryan-Huang1** [comment]
I had this exact same issue. In this [article](https://www.megavoxels.com/2019/08/how-to-install-magica-voxel.html) it recommends to "drag the MagicaVoxel.app file outside of the folder that it came in. Then drag it back into the folder again". I tried this and it worked perfectly for me.
