### ISSUE TITLE
Tricky personal palette

### ISSUE THREAD

**Issue by MiniHarlock** [ephtracy/ephtracy.github.io#206]
Hi,
I downloaded and installed MagicaVoxel-0.99.6.2-macos-10.15 yesterday to be used with Catalina.
Something is bothering me: in case I set a color in my personal palette tab, then click save, then select another palette tab for a second, my personal color(s) just turn back to grey whenever I get back to my personal palette tab. See what I mean?
My personal palette IS saved and well loaded each time I open a project. But as soon as I click on another tab and then get back to it, it just gets blank again…
Is that a bug or something that I don't understand?
Thank you for your help.

**Comment by ephtracy** [comment]
the palette buttons 0/1/2/3 are used to load the default palettes stored in the palette/ folder. It has nothing to do with your saved palette in the model.

**Comment by MiniHarlock** [comment]
Thank you for your answer.
OK, so how can I create a personal palette?

**Comment by ephtracy** [comment]
there are three buttons below the palette that can save/load/new palettes.
