### ISSUE TITLE
Question: how to group objects?

### ISSUE THREAD

**Issue by MiniHarlock** [ephtracy/ephtracy.github.io#207]
Hi there,
This one is not an issue as such (well… I hope it is not…) but more a question. Very sorry if this place is not intended for asking questions, but I can't find any MV forum on the net!
Right now I'm still wondering about MANY things about MV, but let's cut it to my main issue: I just can't find a way to group voxels in my Model window. Let's say I want to create a scene with a truck and a car (and even much more actually). After I'm satisfyed with the car, I'd like to make a group of it, so that I can select it with one click and maybe move it. Maybe I'm missing the MV philosophy, but I think this should be some basic operation most users would need, right? But I can't find it anywhere :-/ Things are more like items are only selected by their colors, which can be useful sometimes, but mostly on some rare occasions.
So could you please let me know what I'm missing? Cause I'm really lost and would like to make some urgent work using MV, which is starting to make me freak out a bit! Not knowing if I should give up before it's too late (so many unclear things to me) or if I should listen to this voice telling me I'm totally in love with MV!
Thank you for your help.

**Comment by MiniHarlock** [comment]
OK, I guess you're too busy to answer questions. So I tried to find out things by myself for hours again without explanations.
Is the idea to create and save objects one by one as models and then gather them in the world editor so that we're free to organize and group them freely?

**Comment by ephtracy** [comment]
there are two buttons on the top bar for group and ungroup objects in the world edit view.
hotkeys: CTRL+R and CTRL+SHIFT+R
