### ISSUE TITLE
#Suggestion: Rather than do CTRL+C and CTRL+V, add doubling (Duplicate)

### ISSUE THREAD

**Issue by bktech2021** [ephtracy/ephtracy.github.io#209]
I think it would be better if it was added to this program.

**Comment by ephtracy** [comment]
you can use SHIFT+Drag for that.

**Comment by bktech2021** [comment]
Not working on me. Changes his location at Y axis.

**Comment by ephtracy** [comment]
it should work in world editor. did you press SHIFT while dragging?

**Comment by bktech2021** [comment]
I'm trying it in MagicaVoxel. Yes, I'm pressing SHIFT key when dragging.

**Comment by bktech2021** [comment]
I will send a video.

**Comment by bktech2021** [comment]
Uploading MagicaVoxel _ Ephtracy 2021-08-11 09-31-33.mp4…
I was pressing SHIFT key when dragging.

**Comment by bktech2021** [comment]
I can't send it. But it doesnt work.

**Comment by ephtracy** [comment]
is it in the world editor?

**Comment by ephtracy** [comment]
ok. the method I mentioned is in the world tab.

**Comment by bktech2021** [comment]
![image](https://user-images.githubusercontent.com/80114298/128984290-d6929fe6-f3ae-48ca-b6cd-b5ee57b7aaeb.png)
Where is the World tab?

**Comment by ephtracy** [comment]
the arrow button besides the model size 40 40 40. (or you can use key TAB to switch between model and scene editor)

**Comment by bktech2021** [comment]
I got it. Thanks.

**Comment by bktech2021** [comment]
I have a question too. What is the MagicaVoxel console commands?

**Comment by ephtracy** [comment]
it is the command line tool: http://ephtracy.github.io/index.html?page=mv_commands
