### ISSUE TITLE
Black Screen on Launch

### ISSUE THREAD

**Issue by maxoakland** [ephtracy/ephtracy.github.io#213]
Running on Mac OS 10.14, Magica displays a black screen on launch and nothing else

**Comment by ziem** [comment]
The same happens on macOS Big Sur 11.4.

**Comment by muhammadsamir11** [comment]
Same here

**Comment by ThatOneBro** [comment]
Had the same issue just now... Try moving the .app file out of the folder and back in, then launch it again. For whatever reason, that seems to fix it for me. Hope that helps.

**Comment by ISebSej** [comment]
Lol that actually fixed it @ThatOneBro

**Comment by rojadesign** [comment]
Well, this issue is well known and the solution to this can be found in the FAQ for years now:
**macOS : Black screen: move magicavoxel.app outside the folder and then move it back.**
