### ISSUE TITLE
Support for Apple M1 Silicon Macs

### ISSUE THREAD

**Issue by JulienLussiez** [ephtracy/ephtracy.github.io#214]
At the moment, MagicaVoxel is very slow/unusable on macs with M1 chip, I hope the software will be updated to work with this architecture. Thanks!

**Comment by huylenq** [comment]
Yes, for some reason things becoming extremely slow when zooming in.

**Comment by DafyddHarvey** [comment]
Not able to run MagicaVoxel at all on my M1 MacBook sadly. Hope there's support soon, I'm very tired of my favourite apps not running on this new architecture! #213

**Comment by atalay1** [comment]
+1 on M1 Mac support

**Comment by stefanrows** [comment]
+1 for M1 Mac Support!

**Comment by pepinto** [comment]
+1 for Apple silicon support! Plz plz plz!!!

**Comment by BonomoF** [comment]
+1 for M1 Mac Support! pls its 25 gen 2022 😳

**Comment by randomairborne** [comment]
If i may ask, why is it suspended?
