### ISSUE TITLE
Break in generated output png when the capture image button is used and background option is set to transparant also output jpg does not work

### ISSUE THREAD

**Issue by nlsvdb** [ephtracy/ephtracy.github.io#215]
Break issue in output png in Magicavoxel 0.99.6.4 and in MagicaCSG ( all versions) when you choose option background transparant.
Output to jpg when capture image in Magicavoxel 0.99.6.4 does not work . No output is generated.
Magicavoxel version 0.99.6.3 and before works fine , only the output to jpg not working applies also in 0.99.6.3.

Computer: Windows 10 Home 21H1
Intel Core I5 
![chr_knight](https://user-images.githubusercontent.com/66520890/130844670-e5bd4028-49e6-4880-ba22-630fab3cb93c.png)
DDR 4 8G
NVDIA GEFORCE GT 730 2GB

**Comment by ephtracy** [comment]
updated 0.99.6.4 to fix the diagonal line issue.

**Comment by nlsvdb** [comment]
Thanks!
