### ISSUE TITLE
Voxel Shader Tool (Sphere or Circle Brush) doesn't work in MagicaVoxel-0.99.6.4-win64

### ISSUE THREAD

**Issue by serbi-pavel** [ephtracy/ephtracy.github.io#218]
The tool for working with spheres (the second tool, hot key "C") does not work in any of the modes (Erase, Paint, Attach). A cube frame appears, but nothing happens inside. Version 099.6.2 works without any problems.

**Comment by serbi-pavel** [comment]
![image](https://user-images.githubusercontent.com/90893798/133785788-202d3c16-42d1-4783-9361-5bdda30275e4.png)
![image](https://user-images.githubusercontent.com/90893798/133785850-4c5257b9-4bb4-4980-bc24-b191793eb36b.png)

**Comment by ephtracy** [comment]
</> is the voxel shader tool not the original circle/square tool.

circle/square tools are combined into the line tool as the geometric tool.

**Comment by serbi-pavel** [comment]
> </> is the voxel shader tool not the original circle/square tool.
> 
> circle/square tools are combined into the line tool as the geometric tool.

but how to make the "</>" tool work like in the previous version of the program? at the moment it does not perform any operations at all, I tested it on different computers, the result is the same. the rest of the instruments are ok

It was very useful, I even wrote a YouTube tutorial on how to create such a model. But subscribers began to write that the </> tool does not work in the new version.

![Glass cube MV mod2PS](https://user-images.githubusercontent.com/90893798/133914667-bd3a847c-3ac4-453e-9757-94934d506387.png)

**Comment by ephtracy** [comment]
did you select any voxel shader in the </> panel on the right (besides the project panel)?

**Comment by serbi-pavel** [comment]
> did you select any voxel shader in the </> panel on the right (besides the project panel)?

Thank you very much! I selected the Sphere and it worked!
But could you enable the default sphere mode in newer versions?

![image](https://user-images.githubusercontent.com/90893798/133916175-e0500242-4daa-4ec0-80ad-2e732440ef4c.png)

**Comment by serbi-pavel** [comment]
> But could you enable the default sphere mode in newer versions?

Or can you make it save the last used shader shape the next time you run it?
