### ISSUE TITLE
Rounded grid shape (RG) - NOT AVAILABLE in 0.99.6.2

### ISSUE THREAD

**Issue by matrash** [ephtracy/ephtracy.github.io#231]
Rounded grid shape (RG)
- the chamfered box type of render shape is not available in latest release.
It is very useful visual. Can we fix it please?
![image](https://user-images.githubusercontent.com/1506654/140814176-40431310-8971-4ab3-b5e7-ed65d205b1e1.png)

**Comment by ephtracy** [comment]
this feature is deprecated.
