### ISSUE TITLE
Program not operable on the M1 mac :( 

### ISSUE THREAD

**Issue by danadongin** [ephtracy/ephtracy.github.io#232]
<img width="256" alt="Screen Shot 2021-11-23 at 2 36 27 PM" src="https://user-images.githubusercontent.com/94937273/143140003-8b1c3e4d-8bfc-46c4-b5cf-7a5a89a71148.png">

**Comment by DimasVoxel** [comment]
do right click -> Open. 
It will ask again, but you will be able to execute anyway.

**Comment by DimasVoxel** [comment]
from https://ephtracy.github.io/ 
FAQ No.3:
macOS : Black screen: move magicavoxel executable outside the folder and then move it back in.

Hope that helps
