### ISSUE TITLE
VCOMP140.DLL (Windows)

### ISSUE THREAD

**Issue by Robot67524** [ephtracy/ephtracy.github.io#235]
Every time I try to open MagicaVoxel (version 0.99.6.4) it says:
MagicaVoxel.exe - System Error
Cannot continue performing code, because couldnt find object VCOMP140.DLL. Reinstalling the program could fix the problem. 
I tried reinstalling a few times, but it doesn't work.

**Comment by jadgekumar** [comment]
Hi @Robot67524 ,
I faced the same issue (using Windows 11) and following the steps below resolved it.

1. Uninstall or delete MagicaVoxel app
2.  Go to https://www.microsoft.com/en-ca/download/details.aspx?id=48145 and download both the files vc_redist.x86 and vc_redist.x64 and run them.
3. Restart your computer
4. Download MagicaVoxel again and run it.

Thanks

**Comment by peepeepoopoocheck12345** [comment]
How do you do it on a non-administrator Account? I Got locked out of mine.
