### ISSUE TITLE
[MagicaVoxel / Bug] Some Shader not working on integrated GPUs

### ISSUE THREAD

**Issue by superfrantv** [ephtracy/ephtracy.github.io#242]
Hello,

i found a bug that on my integrated gpu (AMD Radeon RX Vega 11 Graphics) most shaders working wrong, best example is the mandelbulb shader. This makes a big program to notebooks..

**Comment by ShekeraIsHere** [comment]
Hi! I am not very well versed in these technical issues, but I have found a way to solve the problem. I copied the mandelbulb from version 0.99.6.2 and renamed it to mandelbulb2, so I moved it to the shader folder of the magicavoxel version I use and now it works! I hope I was helpful ^^

**Comment by flowbirdsafebird** [comment]
Hey. I have actually been having this same problem. I have tried the solution suggested above but it doesn't seem to work for me. I have a Intel Core i5 GPU. Not really sure what the problem is.

**Comment by AnoyRC** [comment]
use the shader mand of 0.99.4.2, working for m
[mand.txt](https://github.com/ephtracy/ephtracy.github.io/files/8648876/mand.txt)
e

**Comment by FredySandoval** [comment]
> use the shader mand of 0.99.4.2, working for me [mand.txt](https://github.com/ephtracy/ephtracy.github.io/files/8648876/mand.txt)

Is Working fine for me too on Linux.  Just copy the file into the shaders folder

**Comment by ephtracy** [comment]
it's a shader compilation issue. to fix it, change
powern(vec3(u), n) to powern(u, n)
in the shader

**Comment by FredySandoval** [comment]
> it's a shader compilation issue. to fix it, change powern(vec3(u), n) to powern(u, n) in the shaders folder

For those that are modifying manually.
`
vec3 powern( vec3 v, float n ) {
	float r = length( v );
	float phi = atan( v.y, v.x );
	float theta = atan( length( v.xy ), v.z );

	r = pow( r, n );
	phi *= n;
	theta *= n;

	return r * vec3(
		sin( theta ) * vec2( cos( phi ), sin( phi ) ),
		cos( theta )
	);
}

// generate a new voxel color index [0, 255] at position v ( v is at the center of voxel, such as vec3( 1.5, 2.5, 4.5 ) )
float map( vec3 v ) {
	float n = max( m_degree, 4.0 );
	
	vec3 center = i_volume_size * 0.5;
	
	float size = min( min( center.x, center.y ), center.z );

	vec3 u = ( v - center ) / size * 1.1;

	for ( int i = 0; i < 8; i++ ) {
		u = powern( u, n ) + u;
	}
	
	return i_color_index * step( length( u ), 2.0 );
}

`

**Comment by FredySandoval** [comment]
It works
```
vec3 powern( vec3 v, float n ) {
	float r = length( v );
	float phi = atan( v.y, v.x );
	float theta = atan( length( v.xy ), v.z );

	r = pow( r, n );
	phi *= n;
	theta *= n;

	return r * vec3(
		sin( theta ) * vec2( cos( phi ), sin( phi ) ),
		cos( theta )
	);
}

// generate a new voxel color index [0, 255] at position v ( v is at the center of voxel, such as vec3( 1.5, 2.5, 4.5 ) )
float map( vec3 v ) {
	float n = max( m_degree, 4.0 );
	
	vec3 center = i_volume_size * 0.5;
	
	float size = min( min( center.x, center.y ), center.z );

	vec3 u = ( v - center ) / size * 1.1;

	for ( int i = 0; i < 8; i++ ) {
		u = powern( u, n ) + u;
	}
	
	return i_color_index * step( length( u ), 2.0 );
}
```

**Comment by ayliv** [comment]
Hi, I use MagicaVoxel version 0.99.6.4 for windows. I tried to use mand shader version 0.99.4.2 but nothing happened. Does anyone have any idea why? Thanks

**Comment by FredySandoval** [comment]
> Hi, I use MagicaVoxel version 0.99.6.4 for windows. I tried to use mand shader version 0.99.4.2 but nothing happened. Does anyone have any idea why? Thanks
Compare it with mine's, if is still not working, yeah, maybe a GPU issue.
```
// console commands
// 'xs mand [n]' : e.g. 'xs mand 8'

// shader inputs
// uniform vec3		iVolumeSize;	// volume size [1-126]
// uniform float	iColorIndex;	// current color index [1-255]
// uniform vec3		iMirror;		// current mirror mode [0-1]
// uniform vec3		iAxis;			// current axis mode [0-1]

// uniform float	iFrame;			// current anim frame index
// uniform float	iNumFrames;		// total num of anim frames

// uniform float	iIter;			// current iteration index

// uniform vec4		iRand;			// random number

// uniform float	iArgs[8];		// user args

// built-in functions
// float voxel( vec3 v );			// get voxel color index at position v

vec3 powern( vec3 v, float n ) {
	float r = length( v );
	float phi = atan( v.y, v.x );
	float theta = atan( length( v.xy ), v.z );

	r = pow( r, n );
	phi *= n;
	theta *= n;

	return r * vec3(
		sin( theta ) * vec2( cos( phi ), sin( phi ) ),
		cos( theta )
	);
}

// generate new voxel color index at position v
float map( vec3 v ) {
	float n = max( iArgs[0], 4.0 );
	
	vec3 center = iVolumeSize * 0.5;
	
	float size = min( min( center.x, center.y ), center.z );

	vec3 u = ( v + 0.5 - center ) / size * 1.1;

	for ( int i = 0; i < 8; i++ ) {
		u = powern( u, n ) + u;
	}
	
	return iColorIndex * step( length( u ), 2.0 );
}
```

**Comment by ayliv** [comment]
Hi, thanks for your quick answer! I copied yours, and here is what I got. 
![Capture d’écran 2022-05-20 134348](https://user-images.githubusercontent.com/105495612/169521944-b7077f5b-9b21-45a8-a292-0ab29873a385.png)

**Comment by ayliv** [comment]
Does someone have any idea why I have this result?

**Comment by Carloscruzvalencia** [comment]
# Resources

Program: MagicaVoxel-0.99.7.0-win64
Graphic card: NVIDIA GTX 1660 ti
Shader file: [mand.txt](https://github.com/ephtracy/ephtracy.github.io/files/8648876/mand.txt)

The default Mandelbulb and the "mand.txt" shader file ``do not work for me``, but with some changes I have managed to make it work somewhat.

## Solution



1. First, I add the shader file:
![1](https://user-images.githubusercontent.com/38656140/233791204-edb5fbce-4130-4348-9a9a-fa59d96de98a.png)


2. After applying the shader file, nothing changes except for some squares appearing:
![2](https://user-images.githubusercontent.com/38656140/233791221-0990c8d0-a4e2-47d2-9ddd-3b1973fd0f3a.png)


3. I then press "Reverse Empty Space" and it appears, but not quite right, it has too many holes:
![3](https://user-images.githubusercontent.com/38656140/233791225-5cb5d154-89f4-4223-a406-ba2d1eb7ebaa.png)


4. I press the "1/2" button to halve the size and fix it, but it becomes too small:
![4](https://user-images.githubusercontent.com/38656140/233791227-09085b8d-3aab-421e-8db9-e315478998c1.png)

5. It just needs to be scaled and it would be ready:
![5](https://user-images.githubusercontent.com/38656140/233791231-0e534b83-6a0b-4838-9cb5-fa5be7e8e4e9.png)


It will still have holes in the interior, but not as many as in example 3.
