### ISSUE TITLE
play button?

### ISSUE THREAD

**Issue by eksynn** [ephtracy/ephtracy.github.io#262]
i just updated to the beta (.99.7) and i was looking at both the dino and the deer animations... and i don't know where the actual play button is, as well as the frame panels.

**Comment by DimasVoxel** [comment]
![image](https://user-images.githubusercontent.com/62283566/154146537-2696aa93-c310-4ef8-b930-78ab2c0c06d7.png)
This arrow here

**Comment by ephtracy** [comment]
you may check the video here: https://www.youtube.com/watch?v=8vSGjhTHZqA&t=29s
