### ISSUE TITLE
Magicavoxel won't start if I have more than one monitor

### ISSUE THREAD

**Issue by nguyenlamlll** [ephtracy/ephtracy.github.io#263]
I have tested this with 0.99.6.4-win64 and 0.99.7.0-win64 versions on my laptop setup. If I use 3 monitors (one of the laptop and 2 external monitors), MagicaVoxel window will not appear/or appear but all black (there is a process running if I check Task Manager).

If I disconnect two monitors and use one monitor only, MagicaVoxel will start.

Is this behavior noted before?

**Comment by theiviaxx** [comment]
There has to be more variables than just the two monitors.  I have 2 monitors on a pc and it works fine.  Might be how the external ones are connecting to the laptop?

**Comment by nguyenlamlll** [comment]
Thanks. This issue is probably irrelevant/has more variables. Now, after a few GPU driver updates (I use NVIDIA), and a few Windows 10 update, I can open Magicavoxel just fine...
