### ISSUE TITLE
Make maximum size more than 256x256x256 or when importing image it will split it into 256chunks automatically

### ISSUE THREAD

**Issue by Valoneu** [ephtracy/ephtracy.github.io#271]
Title

**Comment by PeakXing** [comment]
yes I need 1024*1024

**Comment by PeakXing** [comment]
> 使用这个我用它来分割图像，然后上传它并安排 https://pinetools.com/split-image

no no no ,I need made 1024*1024 size model.

**Comment by Valoneu** [comment]
well the only way for that is to have 4x4 256x256 cubes
