### ISSUE TITLE
Unable to load MagicaVoxel after install

### ISSUE THREAD

**Issue by rescueranjazz** [ephtracy/ephtracy.github.io#277]
![image](https://user-images.githubusercontent.com/3621479/172181754-65e2d8b5-2c85-4973-b33d-468e983eb4fc.png)

**Comment by rescueranjazz** [comment]
I was able to resolve this issue by downloading the missing files directly from Windows at https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170. 
![image](https://user-images.githubusercontent.com/3621479/172190623-bc259a8c-c13c-4af5-80de-ee9ec9bbd396.png)

Use the 3rd link, the 1st did not load for me.

I hope this helps someone.

**Comment by DimasVoxel** [comment]
I think if you were able to fix the issue you should close the issue as well

**Comment by rescueranjazz** [comment]
Issue resolved.
