### ISSUE TITLE
If Blank Screen On Mac, Use This Trick...

### ISSUE THREAD

**Issue by enzyme69** [ephtracy/ephtracy.github.io#29]
Similar to _**Blender 3D**_, running awesome App like _**Magica Voxel**_ sometimes does not properly on Mac OS. You open the app and getting blank.

If that happens to you, you can use this method, running it from inside the package "Show Package Content". It will open Terminal but that is ok.

<img width="485" alt="screen shot 2017-12-26 at 11 48 32 am" src="https://user-images.githubusercontent.com/3952687/34343928-baabb4ac-ea32-11e7-9af5-9e856dbaedde.png">

<img width="480" alt="screen shot 2017-12-26 at 11 53 22 am" src="https://user-images.githubusercontent.com/3952687/34343966-6769f226-ea33-11e7-91b7-b6b2e7b5b07b.png">

**Comment by TheDaftJet** [comment]
Well, it still won't open for me.
![Screen Shot 2020-04-09 at 8 28 40 AM](https://user-images.githubusercontent.com/63265171/78912166-2116f300-7a3c-11ea-9cf1-d0ef3856a6fc.png)
