### ISSUE TITLE
File handle left open after export

### ISSUE THREAD

**Issue by nobuyukinyuu** [ephtracy/ephtracy.github.io#294]
Quick but annoying bug, I tried exporting 2d png, created new folder in the save dialog box, and saved png there as a test.  Afterwards, I went to delete the folder but couldn't do so because the folder's handle was still being held by MagicaVoxel.  Confirmed the process and that the folder itself was being held causing the issue using procexp;  the handle on the exported file seemed to be released fine after export.

Edit:  System is Windows 10

**Comment by ephtracy** [comment]
this bug will be fixed in 0.99.7.2.
