### ISSUE TITLE
C++ Source Code location?

### ISSUE THREAD

**Issue by lonnietc** [ephtracy/ephtracy.github.io#299]
Hello,

As I understand, Magic Voxel is open source and I am presuming it to be written in C++ but cannot confirm this.

I wanted to see if I could download the source code and compile it locally on my Windows 10 (x64) machine that is using Visual Studio 2019.

I downloaded the github repo but cannot seem to locate the C++ code.

Can you please advise?
Thanks and have a great day

**Comment by aiekick** [comment]
where you understood than this project is open source haha ?
Its indeed a closed source software where github is used for issue and release sotring.
and i have some about doubt about an open source opening one day.

**Comment by lonnietc** [comment]
My mistake. Sorry for the confusion on this .
Thanks again
