### ISSUE TITLE
Blank application window on MacOS 10.12.6

### ISSUE THREAD

**Issue by m0nas** [ephtracy/ephtracy.github.io#31]
Tried both 0.99a and 0.98.2 - application starts, the top menu is present, but the application window remains black and blank - no interface. Opening .vox file makes no difference either.

**Comment by darkfall** [comment]
macOS Users
If you get black screen on macOS Sierra, try this:
extract the whole folder
move "MagicaVoxel.app" outside the folder and then back to it

**Comment by m0nas** [comment]
worked! Thank you
