### ISSUE TITLE
The material sliders don't update when loading a different .vox file.

### ISSUE THREAD

**Issue by bartwe** [ephtracy/ephtracy.github.io#315]
The Material (under Matter in the Render page) sliders don't update when loading a different .vox with different colors.

Repro steps:

- go to Render mode (top right)
- select a color in the Palette view
- select the Blend mode in the 'Material' group on the 'Matter' group which is on the 'Show Material Settings' mode

[optional, this also works if the other .vox has a different value than the current .vox]
- move the 'Roughness' slider to some other value
- open a different .vox file using 'Open Project'
- don't save the changes to the initial file

* notice that the slider hasn't reset to the value that is active in the now open file.

**Comment by toketsupuurin** [comment]
This one can be pretty confusing.

**Comment by ephtracy** [comment]
This bug will be fixed in 0.99.7.2.
