### ISSUE TITLE
Model view without lighting

### ISSUE THREAD

**Issue by xarpen** [ephtracy/ephtracy.github.io#318]
Hi, I'm trying to create a voxel based on the PRB albedo texture that I've downloaded from the Quixel store.

When comparing colors from the image editor to the MagicaVoxel one, it seems that there is some sort of lighting applied, and the color is ever so slightly (5-10%) different.

Is there any way to disable the lighting in the Model view?

P.S. Not to promote anything, but I've created a plugin for native support for vox format for Unity (without any export) if you want to check it [here](https://github.com/xarpen/Vox)

And big thanks for the best voxel editor!

<img width="832" alt="image" src="https://github.com/ephtracy/ephtracy.github.io/assets/36118259/ec4a1e63-a612-4716-a950-074be94ff2d7">

**Comment by ephtracy** [comment]
you can go to Brush->Setting and enable Constant Shading

**Comment by ivan-trackman** [comment]
Very cool, thank you!
Any chance we can get 0.99.7 for mac?
