### ISSUE TITLE
Import qubicle .qb files

### ISSUE THREAD

**Issue by SamLebarbare** [ephtracy/ephtracy.github.io#34]
Asked by community:

Import qubicle files,

i found that:
http://minddesk.com/wiki/index.php?title=Qubicle_Constructor_1:Data_Exchange_With_Qubicle_Binary

**Comment by ephtracy** [comment]
It already supports importing qb file 
1. drag n' drop model to palette view to generate a palette
2. drag n' drop model to model view to generate model
but will support better in future releases

**Comment by SamLebarbare** [comment]
Thx for your response

2018-01-08 20:55 GMT+01:00 ephtracy <notifications@github.com>:

**Comment by SamLebarbare** [comment]
@ephtracy fyi 
I have opened this facebook page  https://www.facebook.com/magicalvoxel/ some times ago when i discover your soft, 
sometimes i get questions by MP, and i make the bridge with github (like this issue)
