### ISSUE TITLE
Request: Unoptimized OBJ exporter

### ISSUE THREAD

**Issue by KakCAT** [ephtracy/ephtracy.github.io#44]
I'm trying to use generate voxel characters and later skin and animate with blender. The problem is that depending on the colors of the character (in same-color zones) the mesh becomes 'too simple' and gives bad results once skinned and animated.

Would it be possible to add an option so that the OBJ is not optimized, maintaining "mesh vertex density"?

Thanks a lot for the software!

**Comment by ephtracy** [comment]
set "config/config.txt->file_obj->optimize" to 0

**Comment by KakCAT** [comment]
wow, great! Thanks a lot :)
