### ISSUE TITLE
Black Screen V 0.99a Mac OS 10.13.3

### ISSUE THREAD

**Issue by ni2020ck** [ephtracy/ephtracy.github.io#54]
V 0.99a Mac OS 10.13.3 High Sierra
Nothing is showing up, just a black screen
<img width="1058" alt="screen shot 2018-02-10 at 4 47 51 pm" src="https://user-images.githubusercontent.com/19882778/36066983-2b5487f6-0e82-11e8-9488-046a06520981.png">

**Comment by JinchengKim** [comment]
same!
How did you solve this problem?

**Comment by sudoio** [comment]
@JinchengKim From the [ephtracy.github.io](https://ephtracy.github.io/) website:
> If you get black screen on macOS Sierra, try this:
> - extract the whole folder
> - move `MagicaVoxel.app` outside the folder and then back to it
