### ISSUE TITLE
Request: Better Duplication

### ISSUE THREAD

**Issue by J5689** [ephtracy/ephtracy.github.io#63]
It can be a pain to duplicate multiple objects in the world view. I think it would be a great idea to add the ability to ALT+DRAG on the gizmo to duplicate the selected object. This is a feature used in Unreal Engine, and it greatly improves workflow for repetitive scenes.

**Comment by ephtracy** [comment]
you can use "Shift+Drag" on the axes or "Ctrl+Shift+Drag" on the object in world editor

**Comment by J5689** [comment]
Wow! Can't believe I didn't figure that out. Thank you!
