### ISSUE TITLE
Big grey "overlap" in render

### ISSUE THREAD

**Issue by Docdoozer** [ephtracy/ephtracy.github.io#65]
![magicavoxelrender](https://user-images.githubusercontent.com/37155818/37111055-0295dfba-223f-11e8-8bb4-d7e36b1cd8bf.JPG)
![magicavoxelnone](https://user-images.githubusercontent.com/37155818/37111056-02b0df40-223f-11e8-8253-f0b5bc40c8f3.JPG)
For some reason everything i render that is big gets this weird gray "overlap" Please help?

**Comment by ephtracy** [comment]
switch to "World" editor and move the object above the ground

**Comment by Docdoozer** [comment]
Ok, thank you!
