### ISSUE TITLE
Request Iso Sprite Export Include Baked AO Option

### ISSUE THREAD

**Issue by Carandiru0** [ephtracy/ephtracy.github.io#72]
I was hoping that the iso export could have an option (say in the config.ini) to include the AO baking WYSIWYG as in the main editor (albeit scaled to the sprites size).

Perhaps also to have Shadowing as another option to toggle on off the shading from the arbritrary lightsource aswell - separate from the enable Baked AO export.

This would be extremely useful in importing assets to an engine, where the sprite is dynamically lit. The sprite being the "texture" over a isometric cube (a mask). Then the AO baking would seamlessly integrate without the extra shadowing of the isometric sprite.

Thanks, and cheers you have made a rock solid app here - I love it.

**Comment by rebelbinary** [comment]
You can just use the screenshot function set the ground/background off and set alpha, and keep the camera at the same angle for every shot to do this.  It would be amazing if we could get a  separate ground shadow sprite from the screen shot, as it's rather difficult to separate the shadows from a white background.  

Magicavoxel would be insanely useful for game asset creators it had an export plugin/script system!
