### ISSUE TITLE
Baking matter / material emission

### ISSUE THREAD

**Issue by kfarr** [ephtracy/ephtracy.github.io#9]
Loving this tool, I was a bit confused how to bake a model that includes material that has emission. The baked model has nice support for the sun light but I can't seem to get the materials to affect the baked output. Am I doing something wrong or is this a known limitation?

**Comment by ephtracy** [comment]
baking option only bakes soft shadow and ambient occlusion to vertex color. material like emission is not supported yet

**Comment by kfarr** [comment]
Ok thanks for clarification. I am trying to bake many files at once using odir command. I was able to get "odir ply" to successfully export the dir at once. However, I was not able to get "odir bake" to do anything. I can do it manually for each as a workaround so it's not a critical issue.

**Comment by ephtracy** [comment]
"bake" is not a "file format" export option, so it's not working with "odir" command

**Comment by kfarr** [comment]
Okay thanks for all the input, closing this ticket as these are not actually bugs.
