### ISSUE TITLE
Source Code...?

### ISSUE THREAD

**Issue by protosam** [ephtracy/ephtracy.github.io#93]
Can we actually get the source code of this application? It seems disingenuous to use github to host a site for an application that we can't view the code for. There's a few reasons for providing the source code, including:  
  
- The ability to ensure the application does not have malware embedded
- People can provide improvements with pull requests (bug fixes, feature additions, etc.)
- If you ever disappear off the face of the earth, other people can pick up the project  
  
Providing the source code does not mean that you have to make the code opensource, you can use a restrictive non-commercial licenses that will allow people to still use the tool to create unrestricted objects, but they can't repackage this application as their own work.  
  
Anyway, thanks for reading this. Please consider throwing the code up.

**Comment by JohnSlaughter** [comment]
It seems arrogant to assume that you have the right to someone else’s code simply because they choose to host it on a repository site designed to host code, both private and Open Source.

I don’t know how others who follow this project feel, but my opinion is that you can take your self-entitled ego and take it somewhere else.

**Comment by protosam** [comment]
While you may think that my initial comment is arrogant. I disagree with you. Regardless of that, let me clarify on this: I'm actually asking if we can just get the source code to vet that it's safe to run.  
  
From what I've seen on youtube, this software looks awesome. However without being able to vet the source code and compile it myself, I don't feel comfortable running it. So this is simply an inquiry requesting the source code and making note on why to supply it.

**Comment by JohnSlaughter** [comment]
Do you make similar requests of Microsoft and Adobe?  It’s very unusual to ask a software developer for their source code.

Further, you literally used the word “disingenuous” to describe the developer for not posting their source code, despite the developer having no obligation to you or anyone to do so.

So yeah, my opinion being equally as irrelevant here, I don’t think you’re request is going to go anywhere. But that’s just my $0.02. I’ll gladly check out now.

**Comment by protosam** [comment]
This software does not appear to be designed for monetization like a Microsoft or Adobe product. Also you're absolutely wrong about it being unusual to as a developer for their source code. On github, it is rare to have to ask for sourcecode, because this is github... The service is designed for collaborative software development. To host a site for an application here does come off as disingenuous use of the service.  
  
You're comparing apples and oranges. Your logic is flawed when it comes to making a request for something (in this case the source code for this application).  
  
At the end of the day, what you have to say doesn't matter here. While you are probably a fine enough human being, you're not providing any value in this specific issue.  
  
If the dude doesn't want to release the source code, so be it. It just sucks because I wont use it unless I can vet the source code for safety. That's my personal stance and my own problem to deal with. However it would be pretty cool to see the source code go up. There's a lot of potential in the project. As it stands, there is no reason not to produce the code. There is nothing to lose from doing so.

**Comment by inferno986return** [comment]
There are a few projects that use GitHub solely for issue management and web hosting, and while I frown a little I don't think it hurts GitHub's EULA.

Anyway I agree that it would be good to see the code as transparency is always benefitial to users and much like CRYENGINE, it doesn't have to be under a libre license: https://github.com/CRYTEK/CRYENGINE

**Comment by protosam** [comment]
I wish @ephtracy would give us a yay or nay. :)

**Comment by Weston-Boldt** [comment]
Pinging this as well, I would also love to see the source

**Comment by jdiperla** [comment]
I think open sourcing it would allow for more and faster modifications to the software. On the other hand, he obviously worked so hard on it that its hard to just open it up for the world to have. It could also make for buggier development and difficult tracking and dev assignment.

**Comment by darkfall** [comment]
What's hosted here is just a Github page, and a convenient place for people to request future features. Its doing nothing against Github EULA. 

If you don't want to donate, its fine, no one asked for your donation. If you want to run it on Linux, there have been a request around for a while but since its a personal project and free App, there is no guarantee it will happen in the near future. Or just go ahead and make yourself one and open source it, there have been voxel engines running on Linux around for a long time.

Currently MagicaVoxel is not a open source project, period.

**Comment by darkfall** [comment]
Closing this as the discussion here going to a wrong discussion, its not against anyone. 

@protosam Please feel free to open a new one requesting the source, in the end its @ephtracy who decides to release the source or not.
